"""add cash balance fields to cash_flow

Revision ID: 11dcdefabe5a
Revises: a6c3c1881294
Create Date: 2026-07-05 19:37:50.419166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dcdefabe5a'
down_revision: Union[str, None] = 'a6c3c1881294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow', sa.Column('cash_at_start', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('cash_flow', sa.Column('cash_at_end', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_flow', 'cash_at_end')
    op.drop_column('cash_flow', 'cash_at_start')
    # ### end Alembic commands ###
