"""create initial tables

Revision ID: 31f86687b92f
Revises: 
Create Date: 2026-07-05 11:47:50.957652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f86687b92f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debtors', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('creditors', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_assets', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('operating_cf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('investing_cf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('financing_cf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('enterprise_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('source_doc', sa.String(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_of_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('operating_loss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_loss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_statement')
    op.drop_table('extraction_log')
    op.drop_table('customer_metrics')
    op.drop_table('cash_flow')
    op.drop_table('balance_sheet')
    op.drop_table('reporting_periods')
    op.drop_table('companies')
    # ### end Alembic commands ###
