"""expand customer_metrics with commercial event

Revision ID: 3f70c0e1cd11
Revises: 11dcdefabe5a
Create Date: 2026-07-05 19:55:58.832871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f70c0e1cd11'
down_revision: Union[str, None] = '11dcdefabe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metrics', sa.Column('new_deals_closed_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('customer_metrics', sa.Column('open_pipeline_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('customer_metrics', sa.Column('notable_commercial_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_metrics', 'notable_commercial_events')
    op.drop_column('customer_metrics', 'open_pipeline_value')
    op.drop_column('customer_metrics', 'new_deals_closed_value')
    # ### end Alembic commands ###
