"""expand balance_sheet with full metric fields

Revision ID: a6c3c1881294
Revises: 31f86687b92f
Create Date: 2026-07-05 19:28:29.675240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c3c1881294'
down_revision: Union[str, None] = '31f86687b92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet', sa.Column('fixed_assets', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('current_assets', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('creditors_due_within_one_year', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('net_current_assets', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('creditors_due_after_one_year', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('share_capital', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('share_premium', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('retained_earnings', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('balance_sheet', sa.Column('total_equity', sa.Numeric(precision=14, scale=2), nullable=True))
    op.drop_column('balance_sheet', 'creditors')
    op.drop_column('balance_sheet', 'cash')
    op.drop_column('balance_sheet', 'debtors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet', sa.Column('debtors', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('balance_sheet', sa.Column('cash', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('balance_sheet', sa.Column('creditors', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_column('balance_sheet', 'total_equity')
    op.drop_column('balance_sheet', 'retained_earnings')
    op.drop_column('balance_sheet', 'share_premium')
    op.drop_column('balance_sheet', 'share_capital')
    op.drop_column('balance_sheet', 'creditors_due_after_one_year')
    op.drop_column('balance_sheet', 'net_current_assets')
    op.drop_column('balance_sheet', 'creditors_due_within_one_year')
    op.drop_column('balance_sheet', 'current_assets')
    op.drop_column('balance_sheet', 'fixed_assets')
    # ### end Alembic commands ###
