"""add depreciation to cash_flow for EBITDA

Revision ID: baff673dba20
Revises: 3f70c0e1cd11
Create Date: 2026-07-06 08:59:39.028116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baff673dba20'
down_revision: Union[str, None] = '3f70c0e1cd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow', sa.Column('depreciation', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_flow', 'depreciation')
    # ### end Alembic commands ###
