"""add interest_expense and principal_due_within_one_year for DSCR

Revision ID: edc3832dfd60
Revises: baff673dba20
Create Date: 2026-07-06 09:38:00.121309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc3832dfd60'
down_revision: Union[str, None] = 'baff673dba20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet', sa.Column('principal_due_within_one_year', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('income_statement', sa.Column('interest_expense', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statement', 'interest_expense')
    op.drop_column('balance_sheet', 'principal_due_within_one_year')
    # ### end Alembic commands ###
